function [str, valid] = enumToString_TestEnum(enumValue)
%#codegen
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeEnumToStringModelPackagedCode('testSerializedParams', 'TestEnum')

    valid = uint8(1);
    coder.varsize('str', [1 12], [false true]);
    switch enumValue
        case TestEnum.eval1
            str = uint8('eval1');
        case TestEnum.eval2
            str = uint8('eval2');
        case TestEnum.eval3_longer
            str = uint8('eval3_longer');
        otherwise
            str = uint8('eval1');
            valid = uint8(0);
    end
end