function bus = initializeBus_TestBusOuter()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   writeInitializeBusModelPackagedCode('testSerializedParams', 'TestBusOuter')

    bus.val1 = zeros([1 1], 'uint8');
    bus.val2 = zeros([5 1], 'uint8');
    bus.valEnum = TestEnum.eval1;
    bus.nested = repmat(testSerializedParamsLib.initializeBus_TestBusInner(), 1);

end