function bus = initializeBus_TestBusInner()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   writeInitializeBusModelPackagedCode('testSerializedParams', 'TestBusInner')

    bus.centerSize = zeros([2 1], 'uint8');
    bus.holdWindowCenter = zeros([1 1], 'uint8');
    bus.holdWindowTarget = zeros([1 1], 'uint16');

end