function [enumValue, valid] = stringToEnum_TestEnum(str)
%#codegen
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeEnumToStringModelPackagedCode('testSerializedParams', 'TestEnum')

    valid = uint8(1);
    if isequal(uint8(str(:)), uint8('eval1')')
        enumValue = TestEnum.eval1;
    elseif isequal(uint8(str(:)), uint8('eval2')')
        enumValue = TestEnum.eval2;
    elseif isequal(uint8(str(:)), uint8('eval3_longer')')
        enumValue = TestEnum.eval3_longer;
    else
        enumValue = TestEnum.eval1;
        valid = uint8(0);
    end
end