function outSize = getSerializedBusLength_ContinuousDataBus(bus, namePrefix)
%#codegen
% DO NOT EDIT: Auto-generated by 
%   writeGetSerializedBusLengthCode('ContinuousDataBus')

    if nargin < 2, namePrefix = uint8(''); end
    namePrefixBytes = uint8(namePrefix(:))';
    outSize = uint32(0);
    % element continuousTimeOffsets
    outSize = outSize + uint32(1); % bit flags
    outSize = outSize + uint32(1); % signal type
    outSize = outSize + uint32(2 + numel(namePrefixBytes) + 21); % for name (including prefix)
    outSize = outSize + uint32(2 + 2); % for units
    outSize = outSize + uint32(1); % for data type id
    outSize = outSize + uint32(1 + 2*1); % for dimensions
    outSize = outSize + uint32(4 * numel(bus.continuousTimeOffsets)); % for continuousTimeOffsets data 

    % element continuousData
    outSize = outSize + uint32(1); % bit flags
    outSize = outSize + uint32(1); % signal type
    outSize = outSize + uint32(2 + numel(namePrefixBytes) + 14); % for name (including prefix)
    outSize = outSize + uint32(2 + 0); % for units
    outSize = outSize + uint32(1); % for data type id
    outSize = outSize + uint32(1 + 2*2); % for dimensions
    outSize = outSize + uint32(8 * size(bus.continuousData, 1) * size(bus.continuousData, 2)); % for continuousData data 


end