function bus = initializeBus_SpikeDataBus()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   writeInitializeBusGeneratedCode('SpikeDataBus')

    coder.varsize('bus.spikeTimeOffsets', 128, true);
    bus.spikeTimeOffsets = zeros([0 1], 'single');
    coder.varsize('bus.spikeChannels', 128, true);
    bus.spikeChannels = zeros([0 1], 'uint8');
    coder.varsize('bus.spikeUnits', 128, true);
    bus.spikeUnits = zeros([0 1], 'uint8');
    coder.varsize('bus.spikeWaveforms', [48 128], [false true]);
    bus.spikeWaveforms = zeros([48 0], 'int16');

end