function bus = initializeBus_ContinuousDataBus()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   writeInitializeBusGeneratedCode('ContinuousDataBus')

    coder.varsize('bus.continuousTimeOffsets', 60, true);
    bus.continuousTimeOffsets = zeros([0 1], 'single');
    coder.varsize('bus.continuousData', [128 60], [true true]);
    bus.continuousData = zeros([0 0], 'double');

end