function bus = initializeBus_CerebusStatisticsBus()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   writeInitializeBusGeneratedCode('CerebusStatisticsBus')

    bus.numDroppedPackets = uint32(0);
    bus.lastPacketNumber = int32(0);
    bus.lastClock = uint32(0);
    bus.clockOffset = single(0);

end