function bus = initializeBus_TestBus()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   writeInitializeBusModelPackagedCode('testBusArray', 'TestBus')

    coder.varsize('bus.centerSize', [3 3], [true true]);
    bus.centerSize = zeros([0 0], 'uint16');
    bus.enum = TestEnum.val1;
    coder.varsize('bus.holdWindowTarget', 30, true);
    bus.holdWindowTarget = zeros([0 1], 'uint8');

end