function [enumValue, valid] = stringToEnum_TestEnum(str)
%#codegen
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeEnumToStringModelPackagedCode('testBusArray', 'TestEnum')

    valid = uint8(1);
    if isequal(uint8(str(:)), uint8('val1')')
        enumValue = TestEnum.val1;
    elseif isequal(uint8(str(:)), uint8('value2')')
        enumValue = TestEnum.value2;
    elseif isequal(uint8(str(:)), uint8('val3_long')')
        enumValue = TestEnum.val3_long;
    else
        enumValue = TestEnum.val1;
        valid = uint8(0);
    end
end