function outSize = getSerializedBusLength_DataLoggerControlBus(bus)
%#codegen
% DO NOT EDIT: Auto-generated by 
%   writeGetSerializedBusLengthModelPackagedCode('testDataLoggerLocal', 'DataLoggerControlBus')

    outSize = uint16(0);
    % element dataStore
    outSize = outSize + uint16(1); % bit flags
    outSize = outSize + uint16(1); % signal type
    outSize = outSize + uint16(1); % concatenation dimension
    outSize = outSize + uint16(2 + 9); % for name
    outSize = outSize + uint16(2 + 4); % for units
    outSize = outSize + uint16(1); % for data type id
    outSize = outSize + uint16(1 + 2*1); % for dimensions
    outSize = outSize + uint16(1 * numel(bus.dataStore)); % for dataStore data 

    % element subject
    outSize = outSize + uint16(1); % bit flags
    outSize = outSize + uint16(1); % signal type
    outSize = outSize + uint16(1); % concatenation dimension
    outSize = outSize + uint16(2 + 7); % for name
    outSize = outSize + uint16(2 + 4); % for units
    outSize = outSize + uint16(1); % for data type id
    outSize = outSize + uint16(1 + 2*1); % for dimensions
    outSize = outSize + uint16(1 * numel(bus.subject)); % for subject data 

    % element protocol
    outSize = outSize + uint16(1); % bit flags
    outSize = outSize + uint16(1); % signal type
    outSize = outSize + uint16(1); % concatenation dimension
    outSize = outSize + uint16(2 + 8); % for name
    outSize = outSize + uint16(2 + 4); % for units
    outSize = outSize + uint16(1); % for data type id
    outSize = outSize + uint16(1 + 2*1); % for dimensions
    outSize = outSize + uint16(1 * numel(bus.protocol)); % for protocol data 

    % element protocolVersion
    outSize = outSize + uint16(1); % bit flags
    outSize = outSize + uint16(1); % signal type
    outSize = outSize + uint16(1); % concatenation dimension
    outSize = outSize + uint16(2 + 15); % for name
    outSize = outSize + uint16(2 + 0); % for units
    outSize = outSize + uint16(1); % for data type id
    outSize = outSize + uint16(1 + 2*1); % for dimensions
    outSize = outSize + uint16(4 * numel(bus.protocolVersion)); % for protocolVersion data 

    % element saveTag
    outSize = outSize + uint16(1); % bit flags
    outSize = outSize + uint16(1); % signal type
    outSize = outSize + uint16(1); % concatenation dimension
    outSize = outSize + uint16(2 + 7); % for name
    outSize = outSize + uint16(2 + 0); % for units
    outSize = outSize + uint16(1); % for data type id
    outSize = outSize + uint16(1 + 2*1); % for dimensions
    outSize = outSize + uint16(4 * numel(bus.saveTag)); % for saveTag data 

    % element nextTrial
    outSize = outSize + uint16(1); % bit flags
    outSize = outSize + uint16(1); % signal type
    outSize = outSize + uint16(1); % concatenation dimension
    outSize = outSize + uint16(2 + 9); % for name
    outSize = outSize + uint16(2 + 0); % for units
    outSize = outSize + uint16(1); % for data type id
    outSize = outSize + uint16(1 + 2*1); % for dimensions
    outSize = outSize + uint16(1 * numel(bus.nextTrial)); % for nextTrial data 


end