function bus = initializeBus_TestBusOuter()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   writeInitializeBusModelPackagedCode('testDataLoggerLocal', 'TestBusOuter')

    bus.val1 = zeros([1 1], 'uint8');
    bus.val2 = zeros([5 1], 'uint8');
    bus.nested = repmat(testDataLoggerLocalLib.initializeBus_TestBusInner(), 1);

end