function bus = initializeBus_TestBus()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   writeInitializeBusModelPackagedCode('testDataLoggerLocal', 'TestBus')

    coder.varsize('bus.centerSize', [255 25], [true true]);
    bus.centerSize = zeros([0 0], 'uint8');
    bus.holdWindowCenter = zeros([1 1], 'uint8');
    coder.varsize('bus.holdWindowTarget', 30, true);
    bus.holdWindowTarget = zeros([0 1], 'uint8');

end