function bus = initializeBus_DataLoggerControlBus()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   writeInitializeBusModelPackagedCode('testDataLogger', 'DataLoggerControlBus')

    coder.varsize('bus.dataStore', 30, true);
    bus.dataStore = zeros([0 1], 'uint8');
    coder.varsize('bus.subject', 30, true);
    bus.subject = zeros([0 1], 'uint8');
    coder.varsize('bus.protocol', 30, true);
    bus.protocol = zeros([0 1], 'uint8');
    bus.protocolVersion = zeros([1 1], 'uint32');
    bus.saveTag = zeros([1 1], 'uint32');
    bus.nextTrial = zeros([1 1], 'uint8');

end